### ISSUE TITLE
你好，我目前在学习epon，请问下这个代码的原文章在哪里可以看到呢？感激不尽！

### ISSUE THREAD

**Issue by liuhongxiao** [zhaojinzhou/epon#2]
建议脱坑。    前景不明朗。

**Comment by zhaojinzhou** [comment]
> 建议脱坑。 前景不明朗。

paper 没有发出去。    后来就放弃了， 所以基本忽略吧。

**Comment by zhaojinzhou** [comment]
> 建议脱坑。 前景不明朗。

你是哪个老师？了解下

**Comment by liuhongxiao** [comment]
> > 建议脱坑。 前景不明朗。
> 
> 你是哪个老师？了解下

等我发现这个方向不好的时候已经不早了，课题已经定了，sad~，工作的时候再改行吧，只求能安全毕业了。
